### ISSUE TITLE
Block_updateSizeAndPosition_worksWhenSizeDivisibleByPow2MaxDepth

### ISSUE THREAD

**Issue by timmyhoa** [jubiiz/ECSE250Tester#3]
Case 4, 5, 9, 10 won't work because with the given size, its not possible to reach max depth hence it should throw an exception.

**Comment by jubiiz** [comment]
There may be something I don't understand: for example case 4: lvl=7, maxDepth=10, size=8. 
Makes lvl=8 have size=4; lvl=9 size=2; lvl=10 size=1; 
no?

**Comment by timmyhoa** [comment]
You are right, too much coding today for me lmao
